name: AHR999 Monitor Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 消除弃用警告

      - name: Set up Python
        uses: actions/setup-python@v5  # 消除弃用警告
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run AHR999 Script
        env:
          WXPUSHER_APP_TOKEN: ${{ secrets.WXPUSHER_APP_TOKEN }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
        run: python main.py
